[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT wsgi:app"
